version: '3.8'

services:
  jwt-app-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env
    volumes:
      # Mount source code for hot reloading
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - jwt-network-dev

networks:
  jwt-network-dev:
    driver: bridge 